### ISSUE TITLE
"<" character not being encoded

### ISSUE THREAD

**Issue by dartg** [AndiDittrich/WordPress.Enlighter#14]
At least on Firefox the following code:

    [c]if (a < 10) {}[/c]

Generates this HTML output:

    <code data-enlighter-language="c" class="EnlighterJSRAW"></code>if (a < 10) {}[/c]

Which obviously doesn't highlight the code. However, the ">" character works as expected:

    [c]if (a > 10) {}[/c]

Generates:

    <code data-enlighter-language="c" class="EnlighterJSRAW">if (a &gt; 10) {}</code>

**Comment by AndiDittrich** [comment]
Dear dartg,
thanks for your report.
i'm currently not sure whats going wrong - maybe it's a bug within WordPress' shortcode handler - i will analyze it.

maybe you can use the "Visual Editor Mode" - it will avoid such problems.

best regards, Andi

**Comment by AndiDittrich** [comment]
Dear dartg,
it seems to be a bug/feature of Wordpress to interpret it as opening html tag - this will break the used [Shortcode API](https://codex.wordpress.org/Shortcode_API)

Generally this issue only occures under the following conditions
1. Text Editor Mode is used instead of "Visual Editor Mode" **AND**
2. With shortcodes **AND**
3. Unescaped HTML characters

If you're only working in Text-Mode you should use the HTML escape sequences (&amp;lt; &amp;gt;) instead
