### ISSUE TITLE
Copying code from enlighter code box includes styling

### ISSUE THREAD

**Issue by tophersimon** [AndiDittrich/WordPress.Enlighter#16]
Our users copy code from the enlighter code box on our support site and paste it into our rich text editors. 

For some reason, it's not copying plan text and including styling. Anything we can do to prevent this?

Here's where they're getting the code: http://support.tave.com/documentation/reference/list-of-available-tokens/

Here's what it looks like pasted: 

![image](https://cloud.githubusercontent.com/assets/3422616/9883834/50f76ec0-5b91-11e5-8940-30fc28561576.png)

![image](https://cloud.githubusercontent.com/assets/3422616/9883845/62c2e648-5b91-11e5-8aa0-fc00f7f799f1.png)

**Comment by AndiDittrich** [comment]
Dear tophersimon

this problem is caused by the WYSIWYG editor. normally these editors try to "copy" the text format from pasted content. 
Therefore Enlighter has the option to switch to unhighlighted "RAW" code on doubleclick or use the new window/raw button.

but it's strange that it shows the html of the highlighted code...normally the colorized text should appear - i believe that something is gone wrong within your editor

generally you have a several options to solve such issue:

* Modifiy your editor (take control of the "paste" event)
* Add an extra "code insert button" like the one used in the Enlighter plugin
* Modify EnlighterJS to switch into "raw" mode by a single click/focus event instead of a doubleclick

best regards, Andi

**Comment by tophersimon** [comment]
Hey Andi,

Thanks for the response. Totally makes sense. 

I ended up just removing the plugin integration from that one page which will keep our users from getting errors. Still using the plugin elsewhere where there is actual code and that works well.

Thanks again.

Topher
