### ISSUE TITLE
File not found: userthemes.cache.php

### ISSUE THREAD

**Issue by andornagy** [AndiDittrich/WordPress.Enlighter#28]
Hey, 

After I installed the plugins, I started getting some weird file not found errors, when the Monarch Social Sharing plugin displays the sharing buttons.

`Warning:  require(/home/andorn5/public_html/webdesignerhut.com/wp-content/plugins/enlighter/cache/userthemes.cache.php): failed to open stream: No such file or directory in /home/andorn5/public_html/webdesignerhut.com/wp-content/plugins/enlighter/class/ObjectCache.php on line 59`

`Fatal error:  require(): Failed opening required '/home/andorn5/public_html/webdesignerhut.com/wp-content/plugins/enlighter/cache/userthemes.cache.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/andorn5/public_html/webdesignerhut.com/wp-content/plugins/enlighter/class/ObjectCache.php on line 59`

I assume this could be some weird caching issue or something.

Additional Information:

- Latest Version of WordPress
- W3 Total Cache Version 0.9.4.1
  - with page cache and minification ( manual )enabled.

**Comment by AndiDittrich** [comment]
Dear Andor,

this error is very very strange, because the Enlighter plugin performs a check before including the cache file:

lines 57..62:
```php
public function load(){
	if (is_file($this->_filename) && is_readable($this->_filename)){
		$this->_storage = require($this->_filename); // line which throws your error
		$this->_dataAvailable = true;
	}
}
```

does the error only occur whem the "Monarch Social Sharing plugin" is activated ?
is the file `enlighter/cache/userthemes.cache.php` available within your webspace ? maybe you can try to set it's chmod to 0770

**Comment by andornagy** [comment]
Hey Andi,

Yes, it appears where Monarch should display share counts. Althou, it only appears from time to time. Not always.

Where can I set the chmod?

**Comment by AndiDittrich** [comment]
you can set chmod permissions with your ftp program or via ssh.
does it also occurs when W3 total cache is disabled ?

my current problem is that i cannot reproduce the error, because the Monarch plugin seems to be a paid plugin, right ?

i will try to change the caching mechanism with the next release using the [WordPress Transient API](https://codex.wordpress.org/Transients_API) to avoid such issues... but currently i'm not sure whats going wrong

**Comment by andornagy** [comment]
I haven't tried, but I'll and let you know. And the file, enlighter/cache/userthemes.cache.php for some reason, doesn't exists on my live site, but on my local one it does.

And yes, Monarch is a pay plugin.

**Comment by AndiDittrich** [comment]
i've pushed the latest dev version (2.12-beta) to the GitHub master branch. the ObjectCache has been replaced by the transient api - maybe this works in your case

**Comment by andornagy** [comment]
Hey

Sorry for the late reply, I tested the new vresion,a nd it gives me the
following error, and breaking the admin area:

*Warning*: file_put_contents(/home/andorn5/public_html/
webdesignerhut.com/wp-content/plugins/WordPress.Enlighter-master/cache/TinyMCE.css):
failed to open stream: No such file or directory in
*/home/andorn5/public_html/webdesignerhut.com/wp-content/plugins/WordPress.Enlighter-master/class/TinyMCE.php
<http://webdesignerhut.com/wp-content/plugins/WordPress.Enlighter-master/class/TinyMCE.php>*
on
line *189*

**Comment by andornagy** [comment]
Hey

Sorry for the late reply, I tested the new vresion,a nd it gives me the
following error, and breaking the admin area:

*Warning*: file_put_contents(/home/andorn5/public_html/
webdesignerhut.com/wp-content/plugins/enlighter/cache/TinyMCE.css): failed
to open stream: No such file or directory
in*/home/andorn5/public_html/webdesignerhut.com/wp-content/plugins/enlighter/class/TinyMCE.php
<http://webdesignerhut.com/wp-content/plugins/enlighter/class/TinyMCE.php>* on
line *189*

**Comment by AndiDittrich** [comment]
Hi,

it was my mistake - i've didn't added any file to the cache directory, therefore it was not under version control and not pushed to GitHub. i have just added an empty file to the directory.

your last error was caused by this missing directory - the plugin tried to write the cache file into it.
this only affects the GitHub releases, not the WordPress Repository

**Comment by AndiDittrich** [comment]
Does it work with the latest v3.0 release ?

**Comment by andornagy** [comment]
Hey

Not using monarch on main site anymore. I'll test it tomorrow on my local
one. And will let u know

**Comment by bryanwillis** [comment]
This was a huge change :+1:  The ObjectCache had issues with WPEngine's cache and would require manual cache flushing every so often. Very happy to see this. Keep up the good work Andi.
