### ISSUE TITLE
Plugin compatibility issues

### ISSUE THREAD

**Issue by bryanwillis** [AndiDittrich/WordPress.Enlighter#30]
Found a few issues with certain plugins I wanted to post.

**My WP Environment**
- WPEngine Nginx/Apache Combo
- Latest Wordpress
- Latest wordpress.org enlighter release

**Issue 1 : Slider Revolution 5.1.6**
- causes the page to overload with console errors and a huge memory hit. Looks like it has something to do with moottools. 

<img width="1222" alt="screen shot 33" src="https://cloud.githubusercontent.com/assets/4042621/13341251/960e10cc-dbfc-11e5-91a8-f747a3748ec0.png">

**Issue 2 : [Asset Queue Manager](https://wordpress.org/support/topic/getting-an-error-because-jquery-isnt-loading)**
- Causes that plugin to break. Asset Queue Manager reports that Jquery is not loaded even though it is.

Anyway, wish I could help here, but these both appear to be javascript errors which if not jquery, is my Kryptonite.

**Comment by AndiDittrich** [comment]
HI Bryan,

**Issue 2**
i've created a fix for the Asset Queue Manager and posted it in the [WordPress.org Forum](https://wordpress.org/support/topic/getting-an-error-because-jquery-isnt-loading?replies=7#post-8083921) maybe it will applied by the author. it is related to MooTools and other Frameworks/Plugins which **extends the Native Types**.

**Issue 1**
I think it's a problem with jQuery and MooTools - maybe some checks are missing or it's a bad js style...
but i have no access to the plugin, so i cannot reproduce the error within my development environment. do you have a public accessable test-site ?

best regards, Andi

**Comment by AndiDittrich** [comment]
Here is my [pull request](https://github.com/NateWr/asset-queue-manager/pull/5) to the Asset Queue Manager Plugin

**Comment by bryanwillis** [comment]
Wow thanks for the super fast reply. I'll create a test site on wpengine this weekend with revslider and send you the credentials.

**Comment by arcivanov** [comment]
@bryanwillis did you solve the RevSlider issue?
