### ISSUE TITLE
R language support request

### ISSUE THREAD

**Issue by WoadZS** [AndiDittrich/WordPress.Enlighter#37]
I have tried many WordPress Syntax Highlighter plugins, and Enlighter is the best.
But I notice that this plugin does not support R, the language for statistical computing.
Could you please add this language to build-in support or tell me how to add this via extension?
BTW, can I edit the theme CSS file to change the theme?

Thanks to your work on this excellent plugin!

**Comment by AndiDittrich** [comment]
Dear WoadZS,

EnlighterJS (the highlighting Engine) has currently no "extra" language support for **R** because it is mostly covered by the [Generic Highlighting](http://enlighterjs.org/Language.Generic.html) which also includes a [R Example](http://enlighterjs.org/Language.Generic.html).

If you like, you can create a new [language support file](https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Language/Template.mylang.js) for EnlighterJS.

Instead of editing the CSS, it is recommended to create a custom theme mentioned in the [FAQ](https://github.com/AndiDittrich/WordPress.Enlighter/blob/master/FAQ.md) and add these file to a directory named `enlighter` within your WordPress Theme directory. It will be auomatically loaded by Enlighter

**Comment by WoadZS** [comment]
Appreciate that, I will check that.
