### ISSUE TITLE
Only works for Admins / Editors

### ISSUE THREAD

**Issue by nexjsystems** [AndiDittrich/WordPress.Enlighter#40]
Afternoon, 

Using this plugin for front end code display (used with bbpress). Everything works fine except today I received an email from a user that the code tabs (css, js, java etc.) do not show up within the TextHTML section of the comments. These buttons display for myself and other admins / editors but not website participants / members. 

Is this intentional or is there a fix?

Cheers,
Andrew

**Comment by AndiDittrich** [comment]
Dear Andrew,

currently, this behaviour is intended, because there are too much buttons added which is very confusing for end-users. therefore the quicktag-buttons are limited to editors/contributors.

i can add an option to the next release to enable the quicktags for all kind of users. 
additionally, a "code insert dialog" is projected for the Text-Editor (via single Quicktag Button) - this will avoid the long list of buttons in the future.

best regards, Andi

**Comment by AndiDittrich** [comment]
Dear Andrew,

i've just added the filter `enlighter_frontend_editing` on request #44 - this also allows you to enable the frontend editing functions for all kind of users

## FILTER::enlighter_frontend_editing ##

**Description:** Forced enabling/disabling of the frontend editing functions. The default value is created by the condition `USER_LOGGED_IN AND (CAN_EDIT_POSTS OR CAN_EDIT_PAGES)`. Useful to bind editing capabilities to special users/groups 

#### Example 2 - Allow all users to use the editing extensions ####

```php
function mm_ejs_frontend_editing($allowed){
      return is_user_logged_in();
}

// add filter
add_filter('enlighter_frontend_editing', 'mm_ejs_frontend_editing');
```

**Comment by nexjsystems** [comment]
You are the man!!

Thanks much.

Andrew
