### ISSUE TITLE
cpp highlighting -  erroneous closed tags

### ISSUE THREAD

**Issue by rrrfer** [AndiDittrich/WordPress.Enlighter#46]
I write:
`#include <sstream>
#include <string>
#include <iostream>
using namespace std;

int main() {
  int value;
  string userString;
  
  stringstream sstr;
  
  cout < < "enter integer: ";
  cin >> userString;
  
  sstr < < userString; // put string into stringstream
  sstr >> value; // read integer from stringstream
  
  if (sstr.fail()) 
    cout < < "wrong input" << endl;
  else
    cout << "your number: " << value << endl;  
}`

And then press "save" button. Your plugin add tags `</iostream></iostream></string></sstream>` in the end. Your will see it when open your message again for edit.

I see it in bbpress. For example in this page: http://pro-prof.com/forums/topic/cplusplus_string_to_number_converting .

Also (I think for the same reason), your plugin modify `` tags (that used in bbpress by default for highlight code.

**Comment by AndiDittrich** [comment]
Dear rrrfer.
Enlighter **does not add** any tags to your content or modifies it. depending on the editor mode (VisualEditor or TextEditor) - the plugin only wraps the content into `<pre>` tags to preserve contents.

how do you have inserted the content, did you use the "enlighter code insert dialog" or did you just paste the content into the visual or text editor ?

**Comment by rrrfer** [comment]
I used only text editor and insert such tags as "[raw][/raw]" and "[cpp][/cpp]".

I do not use visual editor, because if i write code with it, and then save - that formatting corrupted.
For example i write:
[cpp]
int main() {
  cout << "hello";
}
[/cpp]

but after "save" i have:
[cpp]
int main() {
cout << "hello";
}
[/cpp]

in second code spaces are removed.

**Comment by AndiDittrich** [comment]
i cannot confirm this issue currently - i've tested your code snipped with

**1. Create a new Post, using Visual Editor Mode + Code Insert Dialog**
![enlighter_github_i46](https://cloud.githubusercontent.com/assets/1474107/17905315/d3571c9a-6972-11e6-8c54-2f133e9a4fd1.jpg)


**2. Create a new BB-Press Post using shortcodes**
![enlighter_github_i46_2](https://cloud.githubusercontent.com/assets/1474107/17905328/e1b9698c-6972-11e6-912b-7bfa99c0c5ae.jpg)

in non of these examples, any content is added.

generally, i recommend to use the visual editor mode, because in text editor mode, you are allowed to post html code. in your case, if you paste **unescaped brackets** like `< >`, WordPress as well as your webbrowser interpret it as **html tags** - this is generally not a plugin issue!

the visual editor mode (this means no shortcodes, use the dialog) provides some internal functions which preserve whitespaces + automatically escape specialchars

**Comment by rrrfer** [comment]
github cropped my message, so code, that you should to paste in message is not right.
Copy code from my post (link in first message) or get text from attached file.
[cpp_code.txt](https://github.com/AndiDittrich/WordPress.Enlighter/files/434684/cpp_code.txt)

**Comment by AndiDittrich** [comment]
Dear rrrfer,
i've copied the code from your website (link within your first post). attached the result - i cannot reproduce your issue.

do you have any other editing plugins enabled ? try the disable all plugins on your test-site - mostly such strange things may caused by other plugins which try to modify the content.

![enlighter_github46_3](https://cloud.githubusercontent.com/assets/1474107/17931215/93469610-6a0a-11e6-9c50-7e1ac5e4a5be.jpg)

**Comment by rrrfer** [comment]
hm, are you use it on bbpress? - I do not have this problem in article on my site, but i have it on bbpress.

**Comment by rrrfer** [comment]
Can i get you abilities for test it on my site?
You need to test it with bbpress. 
I can't use editor mode with bbpress, because where user create topic or message in forum - he use text editor and his message corrupts.

But if I use standard bbpress highlight - it works without this bug. The bugs appear where I try to use tags of your plugin.

**Comment by rrrfer** [comment]
Now I see on your last screenshots and seen new bug.
Where i try to publish such message:
<pre>
#include <iostream>
using namespace std;

int main() {
  int value;
  
  cout << "enter integer value: ";
  cin >> value;
  
  if (cin.fail())
    cout << "fail" << endl;
  else 
    cout << "your value: " << value << endl;
}
</pre>

your plugin add spaces:
<pre>cout < < "enter integer value: ";
cout < < "fail" << endl;</pre>

but in this case all work fine:
<pre>
cout << "your value: " << value << endl;
</pre>

It's serious bug, because code with spaces is wrong (compilation error).

**Comment by rrrfer** [comment]
Can i show you this process (how i make such result) by skype, for example?

**Comment by AndiDittrich** [comment]
thats very weird, because everythink works fine on my relese testing site using:

**Testing Site Settings**

* WordPress 4.6
* Theme: TwentySixteem
* Plugins: Enlighter
* Enlighter Shortcode Mode: Enlighter Lowlevel
* Enlighter bbPress Integration: enabled

i can test it on your "testing" site or maybe it is better if you can create a screencast from the process, because other users with the same problem can also see it here on github.

did you tried to disable **all other plugins** on your site and switch to another theme ?

currently, i believe it is a problem with another plugin/theme but it is also possible that this is caused by a strange error within Enlighter. **i am very interested in solving this issue!**

i've just copied the (wrong) whitespaces from your site, attached new screenshots from bbPress without them.

### My Testing Results with bbPress ###

**1. Testsnippet**
```
[cpp]
#include <sstream>
#include <string>
#include <iostream>
using namespace std;
int main() {
  int value;
  string userString;
  
  stringstream sstr;
  
  cout << "enter integer: ";
  cin >> userString;
  
  sstr << userString; // put string into stringstream
  sstr >> value; // read integer from stringstream
  
  if (sstr.fail()) 
    cout << "wrong input" << endl;
  else
    cout << "your number: " << value << endl;  
}
[/cpp]
```

**2. New bbPress Response**
![create_bbpress_response](https://cloud.githubusercontent.com/assets/1474107/17960297/7c226f72-6aa5-11e6-8870-3b9bb29c76c1.jpg)

**3. bbPress Result**
![bbpress_result](https://cloud.githubusercontent.com/assets/1474107/17960300/84f35d1e-6aa5-11e6-8a73-c9a51172a0a7.jpg)

**Comment by rrrfer** [comment]
I disable all plugins except bbpress and Enlighter.
I write message:
![2016-08-25 19-42-52](https://cloud.githubusercontent.com/assets/21195729/17967947/47fc8fbc-6adb-11e6-8358-e455acd4f31a.png)

Press "save", and read message:
![2016-08-25 19-43-20](https://cloud.githubusercontent.com/assets/21195729/17967971/57a949aa-6adb-11e6-832a-59f8bbf05ff4.png)

You can see that <ElementType> was changed on Array<elementtype> and such code do not compiled now. 

Then I press "edit" button:
![2016-08-25 19-45-40](https://cloud.githubusercontent.com/assets/21195729/17968027/9220cd9c-6adb-11e6-857f-fec52472ba76.png)

You can see, that in the end of message added close tags:
`</elementtype></class>`

**Comment by rrrfer** [comment]
Now I use only 2 plugins - bbpress 2.5.10 and Enlighter 3.1.
Enlighter settings:
* Enable the_content
* Enable comments
* Enable Language Shortcodes
* Enable Inline Syntax Highlighting
* Visual Editor -> Enable Backend Integration
* Visual Editor -> Enable Frontend Integration
* Visual Editor -> Automatic Width (max)
* Visual Editor -> Add Editor Formats
* Text Editor -> Enable Backend Integration
* Text Editor -> Enable Frontend Integration
* Text Editor -> QuickTag Mode
* Extensions -> bbPress -> Enable Enlighter Shortcode
* Options -> Include Enlighter-CSS
* Options -> Include Enlighter-Javascript

**Comment by rrrfer** [comment]
I tested it on several themes, includes Twenty Sixteen.

**Comment by AndiDittrich** [comment]
I think i've found the issue - the **deprecated** option `use_balanceTags` seems to be enabled in your blog right ? it has been removed from WordPress in v2.0, because it has caused a lot of problems with other plugins.

on every update the settings keep stored in your database. in case you have your blog for a long time and you enabled this option in the past, this would be the reason for that unexpected behaviour

**Comment by rrrfer** [comment]
Thank you. I love you and your plugin :)

**Comment by AndiDittrich** [comment]
I've just added an environment check to the upcoming release to avoid this issue in the future.

![environment_check](https://cloud.githubusercontent.com/assets/1474107/18140922/cd493266-6fb7-11e6-8094-68704f29ddb0.png)
