### ISSUE TITLE
bug with c++ templates (bbpress)

### ISSUE THREAD

**Issue by rrrfer** [AndiDittrich/WordPress.Enlighter#47]
If I try to insert code with C++ templates (example of the post I attached to issue) - your plugin closed tags (but it is not tags - it's templates!).
[cpp_templates.txt](https://github.com/AndiDittrich/WordPress.Enlighter/files/432610/cpp_templates.txt)

On attached pictures you can see that plugin modify my post (change "ElementType" to "elementType") and closed it. It's bug, and i can't now use this plugin ((. 

Resolve this problem please.

![2016-08-23 22-10-22](https://cloud.githubusercontent.com/assets/21195729/17895272/a111455e-695d-11e6-9c46-8cd618c9e4bb.png)

**Comment by AndiDittrich** [comment]
see #46

**Comment by rrrfer** [comment]
I see #46 but there are different problems.Your plugin modify message - it's problem of THIS issue. You can see it on screenshots. I post message with <ElementType> but plugin modify to <elementtype> and closed this tags (BUT IT IS NOT TAG - its part of code).

**Comment by AndiDittrich** [comment]
not really - it currently looks like that you are switching between text and visual editor mode and you did not take care of html specialchars. 

the wordpress editor is interpreting your code as **html** and adds closing tags - therefore the highlighting is broken.

could you please exactly discribe how do you inserting/editing content - step by step ? 

in the past there were a lot of bug reports like yours and everytime it was a problem caused by the editor usage. it can also be a cross plugin conflict or something else but i cannot reproduce your error without a working example page...
