### ISSUE TITLE
Enlighter Code Settings Button

### ISSUE THREAD

**Issue by mowens3** [AndiDittrich/WordPress.Enlighter#62]
I am seeing an issue when I select a code snippet in the Visual tab.

The Icon attached in the visual builder brings up a modal form, but clicking "OK" does not save changes.

If I use the icon for "Enlighter Code Settings" in the TinyMCE menu changes are saved properly. 

I'm not seeing any JavaScript errors. Running the latest version of WordPress and Enlighter.

**Comment by AndiDittrich** [comment]
Dear Matthew,

thanks for your report! currently, i **cannot reproduce** your issue (Enlighter 3.3, 3.4, WordPress 4.7.3).
It seems to be a very strange issue, because both "buttons" are using the same backend function to show the dialog and apply the changes.

Did you tried to disable all other plugins ? Which Browser/OS (Version) do you use ?

best regards, Andi

**Comment by convergencetech** [comment]
Thanks for your response. It gave me an idea to check out my W3 Total Cache plugin. 
I found the solution was disabling Minify for logged in users.

Performance >> Minify 

Enabled checkbox:
**Disable minify for logged in users**
Authenticated users will not receive minified pages if this option is enabled.

Everything is working great now. Please mark this as resolved.

Thank you.

**Comment by mowens3** [comment]
Thanks for your response. It gave me an idea to check out my W3 Total Cache plugin.
I found the solution was disabling Minify for logged in users.

Performance >> Minify

Enabled checkbox:
Disable minify for logged in users
Authenticated users will not receive minified pages if this option is enabled.

Everything is working great now. 

Thank you.
