### ISSUE TITLE
Change Enlighter Inline Style/Custom Theme

### ISSUE THREAD

**Issue by chris-relaxing** [AndiDittrich/WordPress.Enlighter#74]
Does Enlighter support inline code highlighting that looks like this? If so, how?

![image](https://user-images.githubusercontent.com/30215910/28935876-7dd470f4-784b-11e7-993f-a3bb9aa11a5c.png)

This example was found here:
https://blog.cloudera.com/blog/2014/09/how-to-translate-from-mapreduce-to-apache-spark/

**Comment by AndiDittrich** [comment]
Of course. you can use the code insert dialog, inline formats or shortcodes

**Comment by chris-relaxing** [comment]
Great to know that it is possible! But I am lost as to how. On the page URL I pasted, they do it like this:

Markup in the text: 
<code>reduce()</code>

Then they have css defined like so:
code {
	background-color: #f7f7f9;
	border: 1px solid #e1e1e8;
	padding: 2px 4px;
}

Where would I have to place this css in Wordpress to make this work on my site, such that I would be able to use a shortcode like <code>..</code> to get this inline style? 
thanks

**Comment by AndiDittrich** [comment]
hi chris,

what editor mode do you use ? Visual Editor or Text Editor ?

**Example 1 - Inline Formats (Visual Editor)**

Just select the text you want to highlight and add the language format

![Enlighter Inline Formats](https://raw.githubusercontent.com/AndiDittrich/WordPress.Enlighter/master/screenshots/screenshot-4.jpg)

**Example 2 - Code Insert Dialog (Visual Editor)**

Use the code insert dialog and select "mode: inline"

![Code Insert Dialog](https://raw.githubusercontent.com/AndiDittrich/WordPress.Enlighter/master/screenshots/screenshot-2.jpg)

**Example 3 - Shortcode Mode (Text Editor Only)**

To use the inline shortcode mode, you have to enable it within the Enlighter Settings Page. Finally, wrap your code in a language shortcode tag **without** linebreaks.

```raw
My text [js]alert("1234");[/js] inline ...
```


**CSS**

you don't need to add any css - Enlighter comes with it's own formats.

**Comment by chris-relaxing** [comment]
I generally use the Visual editor. I see that I can use Inline-Code editing like this:

![image](https://user-images.githubusercontent.com/30215910/28999009-bfc7d230-79fe-11e7-8eef-1525461f9b48.png)

And in the Visual editor it looks like this:
![image](https://user-images.githubusercontent.com/30215910/28999019-e6b3a20c-79fe-11e7-86be-2ae2f75cc3db.png)

which produces something that looks kind of like what I want:
![image](https://user-images.githubusercontent.com/30215910/28999025-03c6fb46-79ff-11e7-8e86-833defb028b0.png)

However, I want the text to be a little larger and the background color to be a little different, closer to what I pasted in the first post above. I have been using the 'Enlighter Code Settings' button and previewing different combinations of Language and Theme to see the results. The problem is this takes a while since there are 29 Languages and 18 Themes. (522 combinations!) 

After trying quite a few of these, the one I pasted above seems to be the closest, but not exactly what I want. 

Note: It would be nice if I could output a page that contains a grid of all Language and Theme combinations to see how inline performs on each, to speed up selection instead of choosing one combo at a time and clicking Preview in Wordpress. This is an idea for a feature enhancement.

If I want to make a change to just mode Inline-Code, language 'Raw code', that would be in Enlighter.JS.min.css I suppose..

**Comment by AndiDittrich** [comment]
Now i understand you issue - you want to create a custom theme to change the styles of the inline-highlighting. And you're right, the default themes are located in `EnlighterJS.min.css` but there is an option to "inject" new themes by a custom css file.

**Step 1**
First of all, you have to select an origin theme you want to modify. for example [minimal](https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Themes/Minimal.css)

The uncompressed css files are available within the [EnlighterJS Repository](https://github.com/AndiDittrich/EnlighterJS/blob/master/Source/Themes/).

**Step 2**
We assume you new theme is getting named **lightgrey** - in this case rename the css file to `lightgrey.css` and **replace** each occurence of **minimal** with **lightgrey**

**Step 3**

To change the inline appearance of **RAW** language (no highlighting, just apply the container styles) you need to modify the following rulesets:

```css
/* generic container styles inline+block */
.lightgreyEnlighterJS, .lightgreyEnlighterJSWrapper{
    font-family: "Droid Sans Mono", "Courier New", Courier, monospace;
}

/* Inline specific container styles */
span.lightgreyEnlighterJS{
    background-color: transparent;
    border: none;
}

/* Default Token Styling - font styling*/
.lightgreyEnlighterJS span{
    font-size: 13px;
    color: #2a2a2a;
}
```

**Step 4**

In your WordPress Theme directory, create a new subdirectory named `enlighter/`. 
Place your `lightgrey.css` theme in this directory and enable Enlighter External Theme support (Enlighter -> Options -> Include External Themes).

Apply the settings. Now your custom theme **lightgrey** will appear in the theme dropdown.


That's it!

**Theme/Language Demo**

The Theme/Language Demos are available on the official [Project Website enlighterjs.org](https://enlighterjs.org/Language.Generic.html).

In my opinion, a grid/matrix comparision would not make sense because it is not the desired way how syntax highlighting works. Normally you choose a theme containing the basic container styles and the token styles can be modified by Enlighter Theme Customizer. Other use cases should be solved by custom themes.
