### ISSUE TITLE
Styling is not showing up on initial page load

### ISSUE THREAD

**Issue by mattdowney** [AndiDittrich/WordPress.Enlighter#78]
Hey there, thanks for this awesome plugin!

I’m having a bit of an issue with it though. When I first visit the page, the content is unstyled. It just looks like plain text. If I refresh the page, the styles kick in and everything looks alright. http://45royale.com/blog/convert-pixels-to-rems/

I’ve included a video so you can see what I mean: https://cl.ly/m2WV

Any idea what’s going on? Any help would be appreciated. Thanks!

**Comment by AndiDittrich** [comment]
Hi Matt,

I've checked your website with Edge, GoogleChrome (win x64, 60.0.3112.90) as well as Firefox (32bit, v54) and everything works fine even on the first visit.

in your video, the issue seems to be caused by missing css classes (**uninitialized** Enlighter codeblocks) - this happens in case the javascript based initialization code fails. Such issues can be caused by js/css optimization plugins which modifies the Enlighter code.

Did your web-console throws any errors ?

best regards, Andi

**Comment by mattdowney** [comment]
Hey Andi,

Because we have a page transition setup on our site, we're controlling which scripts execute on page load vs. it just happening automatically. We figured it out after realizing the issue didn't occur when you went directly to the post, but only after arriving there from a previous page. To fix it we just updated our setup to manually initialize the plugin as part of our page load script. Problem solved!

Thanks for your quick response,

Matt
